In [3]:

import pandas as pd
import numpy as np
from sklearn.metrics import classification_report,confusion_matrix

###reading data
missing_value=['?']
data2= pd.read_csv("EC-H1-train.csv", na_values=missing_value)
data1= pd.read_csv("EC-H1-test.csv", na_values=missing_value)
##replacing
# bmedian = data2['Bare Nuclei'].median()
# data2['Bare Nuclei'].fillna(bmedian,inplace=True)

X_train=data2.values[:,1:]
y_train=data2.values[:,0]
X_test=data1.values[:,1:]
y_test=data1.values[:,0]
# y=np.array([1 if yinstance==4 else 0 for yinstance in y ])



###### Devide data to test and train
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


############## Regression with MLP#############
#######sklearn.neural_network.MLPRegressor
# from sklearn.neural_network import MLPRegressor
#
# MLPRegressor(hidden_layer_sizes=(100, ),activation='relu',solver='adam',
# 				alpha=0.0001, batch_size='auto',
#               learning_rate='constant',learning_rate_init=0.001,
#                 power_t=0.5, max_iter=200, shuffle=True,
#               random_state=None, tol=0.0001, verbose=False,
# 				warm_start=False,momentum=0.9,
#               nesterovs_momentum=True, early_stopping=False,
# 				validation_fraction=0.1, beta_1=0.9, beta_2=0.999,
#               epsilon=1e-08,	n_iter_no_change=10)


'''
hidden_layer_sizes=(100,12,45 )
activation=
'identity', no-op activation, useful to implement linear bottleneck, returns f(x) = x
'logistic', the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).
'tanh', the hyperbolic tan function, returns f(x) = tanh(x).
'relu', the rectified linear unit function, returns f(x) = max(0, x)

solver=
'lbfgs' is an optimizer in the family of quasi-Newton methods.
'sgd' refers to stochastic gradient descent.
'adam' refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba

alpha: L2 penalty (regularization term) parameter.
batch_size='auto': When set to 'auto', batch_size=min(200, n_samples)
learning_rate: 'constant', 'invscaling', 'adaptive'    Only used when solver='sgd'.
max_iter : int, optional, default 200
warm_start : bool, optional, default False
momentum : float, default 0.9   only used when solver='sgd'.
validation_fraction : float, optional, default 0.1
beta_1 : float, optional, default 0.9   when solver='adam'
beta_2 : float, optional, default 0.999   when solver='adam'
'''

############## Classification with MLP#############
########sklearn.neural_network.MLPClassifier
from sklearn.neural_network import MLPClassifier
# MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
#               beta_1=0.9, beta_2=0.999, early_stopping=False,
#               epsilon=1e-08, hidden_layer_sizes=(5, 2),
#               learning_rate='constant', learning_rate_init=0.001,
#               max_iter=200, momentum=0.9, n_iter_no_change=10,
#               nesterovs_momentum=True, power_t=0.5, random_state=1,
#               shuffle=True, solver='lbfgs', tol=0.0001,
#               validation_fraction=0.1, verbose=False, warm_start=False)

clf = MLPClassifier(solver='adam', alpha=1e-5,
                     hidden_layer_sizes=(100, 200), random_state=0)
clf.fit(X_train, y_train)

predict =clf.predict(X_test)

print([coef.shape for coef in clf.coefs_])
print(clf.predict_proba(X_test))
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_test,predict, pos_label=2)
mlpauc= metrics.auc(fpr, tpr)

fpr, tpr, thresholds = metrics.precision_recall_curve(y_test,predict, pos_label=2)
mlpaupr= metrics.auc(fpr, tpr)
print(mlpaupr)

#Currently, MLPClassifier supports only the Cross-Entropy loss function
#MLPClassifier supports multi-class classification by applying Softmax as the output function
clf = MLPClassifier(solver='adam',hidden_layer_sizes=(15,), alpha=1e-5, random_state=0)
mlp = clf.fit(X_train, y_train)

predictions = mlp.predict(X_test)
print([coef.shape for coef in clf.coefs_])
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(len(mlp.coefs_))
print(len(mlp.coefs_[0]))
print(len(mlp.intercepts_[0]))



[(16, 100), (100, 200), (200, 1)]
[[0.49457948 0.50542052]
 [0.49457948 0.50542052]
 [0.49457948 0.50542052]
 ...
 [0.49457948 0.50542052]
 [0.49457948 0.50542052]
 [0.49457948 0.50542052]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00       655
         1.0       0.48      1.00      0.65       610

   micro avg       0.48      0.48      0.48      1265
   macro avg       0.24      0.50      0.33      1265
weighted avg       0.23      0.48      0.31      1265

[[  0 655]
 [  0 610]]
nan


c:\program files\python36\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\program files\python36\lib\site-packages\sklearn\metrics\ranking.py:656: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  UndefinedMetricWarning)
c:\program files\python36\lib\site-packages\sklearn\metrics\ranking.py:526: RuntimeWarning: invalid value encountered in true_divide
  recall = tps / tps[-1]


[(16, 15), (15, 1)]
              precision    recall  f1-score   support

         0.0       0.52      1.00      0.68       655
         1.0       0.00      0.00      0.00       610

   micro avg       0.52      0.52      0.52      1265
   macro avg       0.26      0.50      0.34      1265
weighted avg       0.27      0.52      0.35      1265

[[655   0]
 [610   0]]
2
16
15


c:\program files\python36\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier(criterion='entropy', max_depth=10)
tree_model = tree_classifier.fit(X_train, y_train)
predict = tree_model.predict(X_test)

# import graphviz
# dot_data = tree.export_graphviz(tree_model, out_file=None)
# graph = graphviz.Source(dot_data)
# graph.render("Autism",view=True)
names = list(data1)
class_names = ['up', 'down']

from IPython.display import Image
import pydotplus
#graphviz==> https://graphviz.gitlab.io/_pages/Download/Download_windows.html

dot_data = tree.export_graphviz(tree_classifier , out_file=None,
                                feature_names=names[1:],
                                class_names=class_names)
graph = pydotplus.graph_from_dot_data(dot_data)

# Show graph
Image(graph.create_png())

# Create pdf
graph.write_pdf("Finance.pdf")

# Create PNG
graph.write_png("Finance.png")


####Confusion matrix
cnf_matrix = metrics.confusion_matrix(predict,y_test )
print(cnf_matrix)

###Metrics
print("Accuracy:",metrics.accuracy_score(y_test, predict))
print("Precision:",metrics.precision_score(y_test, predict))
print("Recall:",metrics.recall_score(y_test, predict))
print("F_measure:",metrics.f1_score(y_test, predict))
print( "classification error is :", np.sum(predict != y_test) / len(y_test) )




########## Bagging method  ######
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
bagging = BaggingClassifier()
bagging_model = bagging.fit(X_train, y_train)

bagging_predict = bagging_model.predict(X_test)
confusion = metrics.confusion_matrix(y_test, bagging_predict)

from colorama import Back, Fore
print(Back.YELLOW)
print("\t\t{0:s} \t {1:s} ".format(Fore.RED + "predicted NO", Fore.RED + "predicted YES"))
print(Fore.GREEN + "actual NO \t {0} \t\t  {1} \t".format(Fore.BLUE + str(confusion[0, 0]), Fore.BLACK + str(confusion[0, 1])))
print(Fore.GREEN + "actual YES \t {0} \t\t  {1} \t".format(Fore.BLACK + str(confusion[1, 0]), Fore.BLUE + str(confusion[1, 1])))

print(Back.CYAN)
print(metrics.classification_report(y_test, bagging_predict))
print(Back.RESET)



########### Random Forest  ###########

random_forest = RandomForestClassifier(min_samples_split=5, min_samples_leaf=2, max_depth=10)
random_forest_model = random_forest.fit(X_train, y_train)

random_forest_predict = random_forest_model.predict(X_test)
print( metrics.confusion_matrix(y_test, random_forest_predict))

print(Back.GREEN)
print(metrics.classification_report(y_test, random_forest_predict))
print(Back.RESET)



[[261 227]
 [394 383]]
Accuracy: 0.509090909090909
Precision: 0.4929214929214929
Recall: 0.6278688524590164
F_measure: 0.5522710886806056
classification error is : 0.4909090909090909

		predicted NO 	 predicted YES 
actual NO 	 328 		  327 	
actual YES 	 300 		  310 	

              precision    recall  f1-score   support

         0.0       0.52      0.50      0.51       655
         1.0       0.49      0.51      0.50       610

   micro avg       0.50      0.50      0.50      1265
   macro avg       0.50      0.50      0.50      1265
weighted avg       0.51      0.50      0.50      1265




c:\program files\python36\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[[287 368]
 [277 333]]

              precision    recall  f1-score   support

         0.0       0.51      0.44      0.47       655
         1.0       0.48      0.55      0.51       610

   micro avg       0.49      0.49      0.49      1265
   macro avg       0.49      0.49      0.49      1265
weighted avg       0.49      0.49      0.49      1265


