In [1]:
############## Classification#############
###########Logistic Regression
import pandas as pd
from sklearn.linear_model import LogisticRegression

# X, y = load_iris(return_X_y=True)
#
# ###### Devide data to test and train
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

data2= pd.read_csv("EC-H1-train.csv")
data1= pd.read_csv("EC-H1-test.csv")
##replacing
# bmedian = data2['Bare Nuclei'].median()
# data2['Bare Nuclei'].fillna(bmedian,inplace=True)

X_train=data2.values[:,1:]
y_train=data2.values[:,0]
X_test=data1.values[:,1:]
y_test=data1.values[:,0]


logreg = LogisticRegression( )
logregmodel = logreg.fit(X_train, y_train)

y_pred = logregmodel.predict(X_test)
# array([0, 0])
print(logregmodel.predict_proba(X_test))
# array([[9.8...e-01, 1.8...e-02, 1.4...e-08], [9.7...e-01, 2.8...e-02, ...e-08]])
logesticRscore = logregmodel.score(X_test, y_test)

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)

######ploting
# import required modules
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
#matplotlib inline
class_names=[0,1] # name  of classes
fig, ax = plt.subplots()
tick_marks = np.arange(len(class_names))
plt.xticks(tick_marks, class_names)
plt.yticks(tick_marks, class_names)

# create heatmap
sns.heatmap(pd.DataFrame(cnf_matrix), annot=True, cmap="YlGnBu" ,fmt='g')
ax.xaxis.set_label_position("top")
plt.tight_layout()
plt.title('Confusion matrix', y=1.1)
plt.ylabel('Actual label')
plt.xlabel('Predicted label')

plt.show()

#####Metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# print("Precision:",metrics.precision_score(y_test, y_pred))
# print("Recall:",metrics.recall_score(y_test, y_pred))

#### Roc Curve
y_pred_proba = logreg.predict_proba(X_test)[::,1]
fpr, tpr, _ = metrics.roc_curve(y_test,  y_pred_proba)
auc = metrics.roc_auc_score(y_test, y_pred_proba)
plt.plot(fpr,tpr,label="data 1, auc="+str(auc))
plt.legend(loc=4)
plt.show()
1+1


c:\program files\python36\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[0.29693337 0.70306663]
 [0.37347574 0.62652426]
 [0.29787613 0.70212387]
 ...
 [0.35343663 0.64656337]
 [0.3619321  0.6380679 ]
 [0.41306273 0.58693727]]
[[435 220]
 [266 344]]


<Figure size 640x480 with 2 Axes>

Accuracy: 0.6158102766798419


<Figure size 640x480 with 1 Axes>

2

In [3]:
############## Classification#############

import pandas as pd
import numpy as np


###reading data
# missValue=['?']
data2= pd.read_csv("EC-H1-train.csv")
data1= pd.read_csv("EC-H1-test.csv")
##replacing
# bmedian = data2['Bare Nuclei'].median()
# data2['Bare Nuclei'].fillna(bmedian,inplace=True)

X_train=data2.values[:,1:]
y_train=data2.values[:,0]
X_test=data1.values[:,1:]
y_test=data1.values[:,0]


In [4]:


###########Logistic Regression#####
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logregmodel = logreg.fit(X_train, y_train)
y_pred = logregmodel.predict(X_test)



########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_pred , y_test )
print(cnf_matrix)

#####Metrics
print("logistic Regression_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))



c:\program files\python36\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[435 266]
 [220 344]]
logistic Regression_Accuracy: 0.6158102766798419
Precision: 0.6099290780141844
Recall: 0.5639344262295082


In [5]:
##########Naive Bayes #########
from sklearn.naive_bayes import GaussianNB

GNB = GaussianNB()
GNBmodel = GNB.fit(X_train, y_train)
y_pred = GNBmodel.predict(X_test)

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_pred,y_test )
print(cnf_matrix)

#####Metrics
print("GaussianNB_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))
print("F_measure:",metrics.f1_score(y_test, y_pred))





###### Classification with Linear Regression######
from sklearn.linear_model import LinearRegression
LR= LinearRegression()
LRmodel = LR.fit(X_train, y_train)
y_regpred = LRmodel.predict(X_test)
y_pred= [1 if x>=0.4 else 0 for x in y_regpred]

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_pred , y_test)
print(cnf_matrix)

#####Metrics
print("Linear Regression_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test , y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))





[[412 253]
 [243 357]]
GaussianNB_Accuracy: 0.607905138339921
Precision: 0.595
Recall: 0.5852459016393443
F_measure: 0.5900826446280992
[[379   0]
 [276 610]]
Linear Regression_Accuracy: 0.7818181818181819
Precision: 0.6884875846501128
Recall: 1.0


In [6]:

######QDA ###########
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
QDA= QuadraticDiscriminantAnalysis()
QDAmodel = QDA.fit(X_train, y_train)
y_pred = QDAmodel.predict(X_test)

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
print(cnf_matrix)

#####Metrics
print("QDA_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test , y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))




c:\program files\python36\lib\site-packages\sklearn\discriminant_analysis.py:692: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
c:\program files\python36\lib\site-packages\sklearn\discriminant_analysis.py:692: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


[[585  70]
 [552  58]]
QDA_Accuracy: 0.508300395256917
Precision: 0.453125
Recall: 0.09508196721311475
[[622  26]
 [ 33 584]]
LDA_Accuracy: 0.9533596837944665
Precision: 0.946515397082658
Recall: 0.9573770491803278


c:\program files\python36\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [8]:


######LDA ###########
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
LDA= LinearDiscriminantAnalysis()
LDAmodel = LDA.fit(X_train, y_train)
y_pred = LDAmodel.predict(X_test)

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_pred ,y_test )
print(cnf_matrix)

#####Metrics
print("LDA_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test , y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))


[[622  26]
 [ 33 584]]
LDA_Accuracy: 0.9533596837944665
Precision: 0.946515397082658
Recall: 0.9573770491803278


c:\program files\python36\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [ ]:


######SVM ###########
from sklearn.svm import SVC
Svm= SVC(C=1.0, kernel='rbf', degree=3, gamma='auto',
 coef0=0.0, shrinking=True, probability=False, tol=0.001,
 cache_size=200, class_weight=None, verbose=False, max_iter=-1,
 decision_function_shape='ovo', random_state=None)

Svmmodel = Svm.fit(X_train, y_train)
y_pred = Svmmodel.predict(X_test)

########Confusion matrix
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_pred ,y_test )
print(cnf_matrix)

#####Metrics
print("SVM_Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test , y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))


c:\program files\python36\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [ ]:
# from sklearn.model_selection import LeaveOneOut
# X = X_train
# y = y_train
# loo = LeaveOneOut()
# loo.get_n_splits(X)
#
#
# for train_index, test_index in loo.split(X):
#    # print("TRAIN:", train_index, "TEST:", test_index)
#    X_train, X_test = X[train_index], X[test_index]
#    y_train, y_test = y[train_index], y[test_index]
#    # print(X_train, X_test, y_train, y_test)
